[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to allow expected environment variables
[build.processing]
  skip_processing = false

# Allow specific environment variables that are expected to be in the build
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Configure secrets scanning
[build.processing.secrets]
  # Allow REACT_APP_OPENAI_API to be in build output (it's expected for client-side use)
  omit_keys = ["REACT_APP_OPENAI_API"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
